import sys
import os
import re


HEADER = """
# Converted Bit script
# Generated by bit_converter.py

from bit_emulator import *
from framebuffer import FrameBuffer, RGB565
import pygame

clock = pygame.time.Clock()

"""


def convert_code(code):

    # Replace Bit import
    code = re.sub(
        r"from Bit import \*",
        "",
        code
    )


    # Replace framebuf import
    code = re.sub(
        r"from framebuf import FrameBuffer, RGB565",
        "from framebuffer import FrameBuffer, RGB565",
        code
    )


    # Remove begin()
    code = re.sub(
        r"begin\(\)",
        "",
        code
    )


    # Convert colors

    colors = {
        "Display.Color.Cyan": "(0,255,255)",
        "Display.Color.Green": "(0,255,0)",
        "Display.Color.White": "(255,255,255)",
        "Display.Color.Black": "(0,0,0)",
        "Display.Color.Red": "(255,0,0)",
        "Display.Color.Blue": "(0,0,255)"
    }


    for old,new in colors.items():

        code = code.replace(
            old,
            new
        )


    # Replace Bit timing with pygame timing

    code = re.sub(
        r"time\.sleep_ms\([0-9]+\)",
        "clock.tick(30)",
        code
    )


    return HEADER + code



def convert_file(filename):

    with open(filename,"r") as f:
        code=f.read()


    converted = convert_code(code)


    output = (
        os.path.splitext(filename)[0]
        +
        "_emu.py"
    )


    with open(output,"w") as f:
        f.write(converted)


    print(
        "Created:",
        output
    )



if __name__ == "__main__":

    if len(sys.argv) < 2:

        print(
            "Usage: python converter.py filename.py"
        )

        exit()


    convert_file(sys.argv[1])
